/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter (ST) for emWin V5.32.                      *
*        Compiled Oct  8 2015, 11:58:22                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: HDU                                                   *
* Dimensions:  64 * 64                                               *
* NumColors:   2                                                     *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmHDU;

#if 0


/*********************************************************************
*
*  This palette is included for reference only
*  As it is saved as device dependent bitmap without color info.
*  Please note that this bitmap requires the physical palette to be
*  identical to the palette of the display.
*  If this does not work out, please convert your bitmap into a DIB 
*/
/*********************************************************************
*
*       Palette
*
*  Description
*    The following are the entries of the palette table.
*    The entries are stored as a 32-bit values of which 24 bits are
*    actually used according to the following bit mask: 0xBBGGRR
*
*    The lower   8 bits represent the Red   component.
*    The middle  8 bits represent the Green component.
*    The highest 8 bits represent the Blue  component.
*/
static GUI_CONST_STORAGE GUI_COLOR _ColorsHDU[] = {
  0x000000, 0xFFFFFF
};

#endif

static GUI_CONST_STORAGE GUI_LOGPALETTE _PalHDU = {
  2,  // Number of entries
  0,  // No transparency
  NULL
};

static GUI_CONST_STORAGE unsigned char _acHDU[] = {
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ____XX__, ________, ________, ________,
  ________, ________, ________, ________, ___XXXX_, ________, ________, ________,
  ________, ________, ________, ________, ___XXXXX, ________, ________, ________,
  ________, ________, ________, ________, ___XXXXX, X_______, ______XX, ________,
  ________, ________, ________, ________, __XXXXXX, XX______, _____XXX, ________,
  ________, ________, ________, ________, __XXXXXX, XXX_____, ____XXXX, ________,
  ________, ________, ____XXXX, ________, _XXXXXXX, XXX_____, __XXXXXX, X_______,
  ________, ________, ____XXXX, XX______, _XXXXXXX, XXXX____, _XXXXXXX, X_______,
  ________, ________, ____XXXX, XXXX____, _XXXXXXX, XXXX___X, XXXXXXXX, X_______,
  ________, ________, ____XXXX, XXXXXX__, _XXXXXXX, XXXXX__X, XXXXXXXX, X_______,
  ________, ________, ___XXXXX, XXXXXXX_, __XXXXXX, XXXXX__X, XXXXXXXX, X_______,
  ________, ________, ___XXXXX, XXXXXXXX, ___XXXXX, XXXXX___, XXXXXXXX, X_______,
  ________, ________, ___XXXXX, XXXXXXXX, X__XXXXX, XXXXXX__, XXXXXXXX, X_______,
  ________, ________, ___XXXXX, XXXXXXXX, XX__XXXX, XXXXXX__, XXXXXXXX, X_______,
  ________, ________, __XXXXXX, XXXXXXXX, XX___XXX, XXXXXX__, XXXXXXXX, X_______,
  ________, ________, __XXXXXX, XXXXXXXX, XXX__XXX, XXXXXX__, XXXXXXXX, X_______,
  ________, ________, _____XXX, XXXXXXXX, XXX___XX, XXXXXX__, XXXXXXXX, X_______,
  ________, ________, ________, XXXXXXXX, XXXX__XX, XXXXXX__, XXXXXXXX, X_______,
  ________, ________, ________, __XXXXXX, XXXX__XX, XXXXXX__, XXXXXXXX, X_______,
  ________, ________, ________, ___XXXXX, XXXXX__X, XXXXXX__, XXXXXXXX, ________,
  ________, ________, ________, ____XXXX, XXXXX__X, XXXXXX__, XXXXXXXX, ________,
  ________, ________, ________, _____XXX, XXXXX__X, XXXXXX__, XXXXXXXX, ________,
  ________, ________, ________, ______XX, XXXXXX_X, XXXXXX__, XXXXXXX_, ________,
  ________, ________, XXXXX___, _______X, XXXXXX__, XXXXXX__, XXXXXXX_, ________,
  ________, _____XXX, XX______, _______X, XXXXXX__, XXXXXX_X, XXXXXXX_, ________,
  ________, __XXXXXX, ________, ________, XXXXXX__, XXXXX__X, XXXXXX__, ________,
  ________, _XXXXX__, ________, ________, XXXXXX__, XXXXX__X, XXXXX___, ________,
  _______X, XXXXX___, ________, ________, XXXXXX__, XXXXX_XX, XXXXX___, ________,
  ______XX, XXXX____, ________, ________, XXXXXX__, XXXX__XX, XXXX____, ________,
  _____XXX, XXX_____, ________, ________, _XXXX__X, XXXX_XXX, XXXX____, ________,
  ____XXXX, XX______, ________, ________, _XXXX__X, XXX__XXX, XXX_____, ________,
  ___XXXXX, XX______, ________, ________, _XXXX__X, XXX_XXXX, XX______, ________,
  ___XXXXX, X_______, ________, ________, XXXX__XX, XX__XXXX, X_______, ________,
  __XXXXXX, X_______, ________, ________, XXXX__XX, X__XXXXX, ________, ________,
  __XXXXXX, X_______, ________, ________, XXX__XXX, X_XXXXX_, ________, ________,
  __XXXXXX, X_______, ________, ________, XXX__XXX, _XXXXX__, ________, ________,
  __XXXXXX, XX______, ________, _______X, XX__XXX_, XXXX____, ________, ________,
  __XXXXXX, XX______, ________, _______X, X__XXX_X, XXX_____, ________, ________,
  __XXXXXX, XX______, ________, ______XX, __XX__XX, X_______, ________, _____X__,
  __XXXXXX, XXX_____, ________, _____XX_, _XX__XX_, ________, ________, ____X___,
  __XXXXXX, XXXX____, ________, ____XX_X, X__XX___, ________, ________, __XX____,
  ___XXXXX, XXXX____, ________, ___X__XX, __X_____, ________, ________, _XX_____,
  ___XXXXX, XXXXXX__, ________, _X__XX__, ________, ________, _______X, XX______,
  ____XXXX, XXXXXXX_, ________, ________, ________, ________, _____XXX, X_______,
  ____XXXX, XXXXXXXX, X_______, ________, ________, ________, ___XXXXX, ________,
  _____XXX, XXXXXXXX, XXX_____, ________, ________, ________, _XXXXX__, ________,
  ______XX, XXXXXXXX, XXXXXX__, ________, ________, _____XXX, XXXXX___, ________,
  _______X, XXXXXXXX, XXXXXXXX, XXXX____, _______X, XXXXXXXX, XXX_____, ________,
  ________, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, ________, ________,
  ________, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__, ________, ________,
  ________, _____XXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____, ________, ________,
  ________, ________, XXXXXXXX, XXXXXXXX, XXXXXXXX, ________, ________, ________,
  ________, ________, ____XXXX, XXXXXXXX, XX______, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, _X___XXX, __XXX__X, XX______, ________, ________,
  ________, ________, ________, _X___X_X, __X____X, ________, ________, ________,
  ________, ________, ________, _X___XXX, __XXX__X, XX______, ________, ________,
  ________, ________, ________, _X_____X, ____X__X, _X______, ________, ________,
  ________, ________, ________, _X___XXX, __XXX__X, XX______, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________
};

GUI_CONST_STORAGE GUI_BITMAP bmHDU = {
  64, // xSize
  64, // ySize
  8, // BytesPerLine
  1, // BitsPerPixel
  _acHDU,  // Pointer to picture data (indices)
  &_PalHDU   // Pointer to palette
};

/*************************** End of file ****************************/
